"""
Hybrid Agent Orchestration Pipeline: Claude (Architect/Reviewer) + Gemini Flash (Worker).

This module coordinates multi-agent workflows where:
1. Claude 3.5 Sonnet creates a structured technical plan.
2. Gemini Flash rapidly writes the implementation or processes heavy context.
3. Claude reviews the code for edge cases, safety, and correctness.
"""

import os
import sys
import argparse
from dataclasses import dataclass
from typing import Optional, Dict, Any


@dataclass
class OrchestrationResult:
    plan: str
    code: str
    review: str
    status: str


class HybridOrchestrator:
    """Orchestrator combining Claude 3.5 Sonnet and Gemini Flash."""

    def __init__(
        self,
        claude_api_key: Optional[str] = None,
        gemini_api_key: Optional[str] = None,
        claude_model: str = "claude-3-5-sonnet-20241022",
        gemini_model: str = "gemini-2.0-flash",
    ):
        self.claude_api_key = claude_api_key or os.environ.get("ANTHROPIC_API_KEY")
        self.gemini_api_key = gemini_api_key or os.environ.get("GEMINI_API_KEY")
        self.claude_model = claude_model
        self.gemini_model = gemini_model

    def _call_claude(self, prompt: str, system_prompt: str = "") -> str:
        """Call Claude model via Anthropic API or fallback mock in dry-run."""
        if not self.claude_api_key:
            return f"[DRY-RUN / MOCK CLAUDE ({self.claude_model})]: Generated response for prompt:\n{prompt[:120]}..."
        
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=self.claude_api_key)
            messages = [{"role": "user", "content": prompt}]
            kwargs: Dict[str, Any] = {
                "model": self.claude_model,
                "max_tokens": 2048,
                "messages": messages,
            }
            if system_prompt:
                kwargs["system"] = system_prompt
            response = client.messages.create(**kwargs)
            return response.content[0].text
        except ImportError:
            return "[ERROR]: 'anthropic' package not installed. Run `pip install anthropic`."
        except Exception as e:
            return f"[CLAUDE ERROR]: {str(e)}"

    def _call_gemini_flash(self, prompt: str) -> str:
        """Call Gemini Flash model via Google GenAI API or fallback mock."""
        if not self.gemini_api_key and not os.environ.get("GOOGLE_API_KEY"):
            return f"[DRY-RUN / MOCK GEMINI FLASH ({self.gemini_model})]: Generated implementation for:\n{prompt[:120]}..."
        
        try:
            # Try new google.genai SDK
            from google import genai
            client = genai.Client(api_key=self.gemini_api_key or os.environ.get("GOOGLE_API_KEY"))
            response = client.models.generate_content(
                model=self.gemini_model,
                contents=prompt,
            )
            return response.text
        except ImportError:
            try:
                # Try google.generativeai fallback
                import google.generativeai as genai_legacy
                genai_legacy.configure(api_key=self.gemini_api_key or os.environ.get("GOOGLE_API_KEY"))
                model = genai_legacy.GenerativeModel(self.gemini_model)
                response = model.generate_content(prompt)
                return response.text
            except ImportError:
                return "[ERROR]: 'google-genai' or 'google-generativeai' not installed. Run `pip install google-genai`."
        except Exception as e:
            return f"[GEMINI FLASH ERROR]: {str(e)}"

    def run_pipeline(self, task_description: str, dry_run: bool = False) -> OrchestrationResult:
        """Execute the full 3-stage Orchestration pipeline."""
        print(f"\n[Hybrid Orchestrator] Starting task: {task_description}")

        # Stage 1: Claude Plans & Architectures
        print("\n--- Stage 1: Claude (Architect) Planning ---")
        if dry_run or not self.claude_api_key:
            plan = (
                f"### Execution Plan\n"
                f"1. Break down '{task_description}' into modular functions.\n"
                f"2. Define input/output contracts and error handling.\n"
                f"3. Prepare unit tests."
            )
        else:
            plan_prompt = f"You are a Principal Software Architect. Create a modular, precise execution plan for the following task:\n\n{task_description}"
            plan = self._call_claude(plan_prompt, system_prompt="You produce clean, structured, actionable specifications.")
        print(plan)

        # Stage 2: Gemini Flash Implements Code
        print("\n--- Stage 2: Gemini Flash (Worker) Code Implementation ---")
        if dry_run or (not self.gemini_api_key and not os.environ.get("GOOGLE_API_KEY")):
            code = (
                f"# Implementation generated by Gemini Flash for:\n# {task_description}\n\n"
                f"def execute_task():\n    print('Task successfully executed.')\n    return True\n"
            )
        else:
            worker_prompt = (
                f"You are an Expert Fast Software Engineer. Implement clean, robust Python code following this specification:\n\n{plan}"
            )
            code = self._call_gemini_flash(worker_prompt)
        print(code)

        # Stage 3: Claude Reviews & Verifies
        print("\n--- Stage 3: Claude (Critic/Reviewer) Verification ---")
        if dry_run or not self.claude_api_key:
            review = "Verification Passed: Code structure matches architectural spec. No security vulnerabilities found."
        else:
            review_prompt = (
                f"Review this code implementation against the specification.\n"
                f"Specification:\n{plan}\n\n"
                f"Code:\n{code}\n\n"
                f"List any bugs, missing edge cases, or optimizations."
            )
            review = self._call_claude(review_prompt, system_prompt="You are a rigorous code reviewer.")
        print(review)

        return OrchestrationResult(
            plan=plan,
            code=code,
            review=review,
            status="SUCCESS",
        )


def main():
    parser = argparse.ArgumentParser(description="Hybrid Agent Orchestrator (Claude + Gemini Flash)")
    parser.add_argument("--task", type=str, default="Implement a packet queue simulator with Rayleigh fading", help="Task description")
    parser.add_argument("--dry-run", action="store_true", help="Run in mock/dry-run mode without live API keys")
    args = parser.parse_args()

    orchestrator = HybridOrchestrator()
    result = orchestrator.run_pipeline(args.task, dry_run=args.dry_run)
    print("\n[Result Status]:", result.status)


if __name__ == "__main__":
    main()
